version: '3.8'

services:
    prod:
        container_name: nestjs_api
        image: nestjs-api:1.0.0
        build:
            context: .
            dockerfile: .
        command: npm run start:prod
        ports:
            - 8000:3000
        networks:
            - nesjs-network
        volumes:
            - .:/workspace
            - /workspace/node_modules
        restart: unless-stopped
        environment: 
          - URL_DATABASE=mongodb://192.168.0.20:49155
          - DB=mongo-fin-api
networks:
    nesjs-network: