version: '3.3'

services:
    producao:
        container_name: fin_api
        build:
            context: .
            dockerfile: DockerFile
        ports:
            - 8005:3001
        restart: unless-stopped
        environment: 
          - URL_DATABASE=mongodb://192.168.0.20:49155
          - DB=mongo-fin-api
